export enum COMMON_EVENTS {
  // User
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  SET_SESSION = "SET_SESSION",
  CLEAR_SESSION = "CLEAR_SESSION",
  SESSION_EXPIRED = "SESSION_EXPIRED",
}
